// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0fMFdZcsvXF_Bls7raX4UUrX5ecm5R6Y',
    appId: '1:678217818367:web:590fc7a9640ef5a2f8acca',
    messagingSenderId: '678217818367',
    projectId: 'gostar-driver',
    authDomain: 'gostar-driver.firebaseapp.com',
    storageBucket: 'gostar-driver.appspot.com',
    measurementId: 'G-PSPCWNR0EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvJ6vxDXcre489Fp9lB3zXPKzFdCz5Hhk',
    appId: '1:678217818367:android:26e5d4714c3b9925f8acca',
    messagingSenderId: '678217818367',
    projectId: 'gostar-driver',
    storageBucket: 'gostar-driver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNND6h2hkAVatGIEFsHtbmBPCE0L4R22w',
    appId: '1:678217818367:ios:f1e4bf3d51af0b69f8acca',
    messagingSenderId: '678217818367',
    projectId: 'gostar-driver',
    storageBucket: 'gostar-driver.appspot.com',
    iosBundleId: 'com.gostar.gostar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNND6h2hkAVatGIEFsHtbmBPCE0L4R22w',
    appId: '1:678217818367:ios:dd2b9c41fb743603f8acca',
    messagingSenderId: '678217818367',
    projectId: 'gostar-driver',
    storageBucket: 'gostar-driver.appspot.com',
    iosBundleId: 'com.gostar.gostar.RunnerTests',
  );
}
